image: node:latest

before_script:
  - apt-get update && apt-get install -y libsecret-1-dev libcurl4-gnutls-dev
  - npm install

stages:
  - test
  - package

test:
  stage: test
  script: npm run test

dist_win:
  stage: package
  image: electronuserland/builder:wine
  script: npm run dist:win
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_SHA-win"
    paths:
      - LICENSE
      - dist/out/*.exe

dist_linux:
  stage: package
  image: electronuserland/builder:10
  script: npm run dist:linux
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_SHA-linux"
    paths:
      - LICENSE
      - dist/out/*.deb
